"""Phase 6 serving support utilities."""

from .config_gen import (
    GeneratedServingConfig,
    ServingConfigRequest,
    generate_phase6_baseline_matrix,
    generate_serving_config,
    normalize_mode,
)
from .baseline_matrix import (
    BaselineMatrix,
    BaselineMatrixError,
    BaselineMode,
    BaselineRunConfig,
    GeneratedConfigBundle,
    build_bifrost_connector_config,
    build_comparison_manifest,
    build_vllm_command,
    generate_baseline_matrix_configs,
    render_lmcache_config_yaml,
)
from .compare import (
    BASELINE_MODES,
    REAL_VLLM_MODES,
    BaselineComparisonConfig,
    BaselineComparisonResult,
    build_comparisons,
    compare_summaries,
    run_baseline_comparison,
)
from .collectors import (
    BifrostMetricsCollector,
    LMCacheMetricsCollector,
    VLLMMetricsCollector,
    bifrost_snapshot_delta,
    extract_lmcache_metrics,
    extract_vllm_metrics,
)
from .request_schema import (
    RequestMetadata,
    ServingRequest,
    read_jsonl,
    request_from_json_line,
    write_jsonl,
)
from .workloads import (
    GeneratedWorkload,
    WorkloadConfig,
    generate_workload,
    normalize_workload_name,
    summarize_workload,
    write_workload,
)
from .env_doctor import (
    CheckResult,
    EnvDoctorConfig,
    EnvDoctorReport,
    ReadinessLevel,
    format_text_report,
    main,
    run_doctor,
)
from .fake_server import FakeOpenAIServer, FakeOpenAIServerConfig, create_server
from .fake_cache_backends import BifrostLMCacheBackend, LocalMemoryCacheBackend, NoCacheBackend
from .http_client import (
    OpenAIClientConfig,
    OpenAICompatibleClient,
    ServingResponseTiming,
    build_request_json,
    parse_response_text,
)
from .metrics import RequestMetricInput, summarize_request_metrics
from .phases import (
    BenchmarkPhase,
    PhaseMetrics,
    PhasePlan,
    PhaseResult,
    build_phase_plans,
    parse_phase_order,
    validate_measured_aggregate,
)
from .orchestrator import (
    OrchestratorConfig,
    OrchestratorResult,
    OrchestratorSafetyError,
    build_processes,
    run_orchestration,
)
from .processes import ManagedProcess, ProcessReadinessTimeout
from .runner import ServingBenchmarkConfig, ServingBenchmarkResult, run_serving_benchmark
from .report import (
    ServingReportConfig,
    ServingReportError,
    ServingReportResult,
    generate_serving_report,
)
from .real_matrix import (
    RealMatrixConfig,
    RealMatrixError,
    RealMatrixResult,
    RealMatrixSafetyError,
    evaluate_completion_gate,
    mode_order_for_repetition,
    preflight_real_matrix,
    run_real_matrix,
)
from .vllm_bench import (
    VLLMBenchAvailability,
    VLLMBenchCommand,
    VLLMBenchRunResult,
    VLLMBenchSafetyError,
    VLLMBenchServeConfig,
    build_vllm_bench_serve_command,
    check_vllm_bench_available,
    dry_run_vllm_bench_serve,
    ingest_vllm_bench_result,
    run_vllm_bench_serve,
)

__all__ = [
    "CheckResult",
    "BASELINE_MODES",
    "EnvDoctorConfig",
    "EnvDoctorReport",
    "FakeOpenAIServer",
    "FakeOpenAIServerConfig",
    "BifrostLMCacheBackend",
    "LocalMemoryCacheBackend",
    "NoCacheBackend",
    "GeneratedServingConfig",
    "GeneratedWorkload",
    "ManagedProcess",
    "OpenAIClientConfig",
    "OpenAICompatibleClient",
    "OrchestratorConfig",
    "OrchestratorResult",
    "OrchestratorSafetyError",
    "ProcessReadinessTimeout",
    "REAL_VLLM_MODES",
    "ReadinessLevel",
    "RealMatrixConfig",
    "RealMatrixError",
    "RealMatrixResult",
    "RealMatrixSafetyError",
    "RequestMetadata",
    "RequestMetricInput",
    "BaselineComparisonConfig",
    "BaselineComparisonResult",
    "BaselineMatrix",
    "BaselineMatrixError",
    "BaselineMode",
    "BaselineRunConfig",
    "BenchmarkPhase",
    "BifrostMetricsCollector",
    "GeneratedConfigBundle",
    "ServingConfigRequest",
    "ServingBenchmarkConfig",
    "ServingBenchmarkResult",
    "ServingReportConfig",
    "ServingReportError",
    "ServingReportResult",
    "ServingRequest",
    "ServingResponseTiming",
    "PhaseMetrics",
    "PhasePlan",
    "PhaseResult",
    "VLLMBenchAvailability",
    "VLLMBenchCommand",
    "VLLMBenchRunResult",
    "VLLMBenchSafetyError",
    "VLLMBenchServeConfig",
    "VLLMMetricsCollector",
    "LMCacheMetricsCollector",
    "WorkloadConfig",
    "bifrost_snapshot_delta",
    "build_request_json",
    "build_bifrost_connector_config",
    "build_comparison_manifest",
    "build_phase_plans",
    "build_processes",
    "build_comparisons",
    "build_vllm_command",
    "build_vllm_bench_serve_command",
    "check_vllm_bench_available",
    "compare_summaries",
    "create_server",
    "dry_run_vllm_bench_serve",
    "extract_lmcache_metrics",
    "extract_vllm_metrics",
    "evaluate_completion_gate",
    "format_text_report",
    "generate_baseline_matrix_configs",
    "generate_phase6_baseline_matrix",
    "generate_serving_config",
    "generate_workload",
    "generate_serving_report",
    "ingest_vllm_bench_result",
    "main",
    "mode_order_for_repetition",
    "normalize_mode",
    "normalize_workload_name",
    "parse_phase_order",
    "parse_response_text",
    "preflight_real_matrix",
    "read_jsonl",
    "request_from_json_line",
    "render_lmcache_config_yaml",
    "run_doctor",
    "run_real_matrix",
    "run_orchestration",
    "run_baseline_comparison",
    "run_serving_benchmark",
    "run_vllm_bench_serve",
    "summarize_workload",
    "summarize_request_metrics",
    "validate_measured_aggregate",
    "write_jsonl",
    "write_workload",
]
