"""Phase 6 serving support utilities."""

from .config_gen import (
    GeneratedServingConfig,
    ServingConfigRequest,
    generate_serving_config,
    normalize_mode,
)
from .compare import (
    BASELINE_MODES,
    REAL_VLLM_MODES,
    BaselineComparisonConfig,
    BaselineComparisonResult,
    build_comparisons,
    compare_summaries,
    run_baseline_comparison,
)
from .request_schema import (
    RequestMetadata,
    ServingRequest,
    read_jsonl,
    request_from_json_line,
    write_jsonl,
)
from .workloads import (
    GeneratedWorkload,
    WorkloadConfig,
    generate_workload,
    normalize_workload_name,
    summarize_workload,
    write_workload,
)
from .env_doctor import (
    CheckResult,
    EnvDoctorConfig,
    EnvDoctorReport,
    ReadinessLevel,
    format_text_report,
    main,
    run_doctor,
)
from .fake_server import FakeOpenAIServer, FakeOpenAIServerConfig, create_server
from .http_client import (
    OpenAIClientConfig,
    OpenAICompatibleClient,
    ServingResponseTiming,
    build_request_json,
    parse_response_text,
)
from .metrics import RequestMetricInput, summarize_request_metrics
from .orchestrator import (
    OrchestratorConfig,
    OrchestratorResult,
    OrchestratorSafetyError,
    build_processes,
    run_orchestration,
)
from .processes import ManagedProcess, ProcessReadinessTimeout
from .runner import ServingBenchmarkConfig, ServingBenchmarkResult, run_serving_benchmark
from .report import (
    ServingReportConfig,
    ServingReportError,
    ServingReportResult,
    generate_serving_report,
)
from .vllm_bench import (
    VLLMBenchAvailability,
    VLLMBenchCommand,
    VLLMBenchRunResult,
    VLLMBenchSafetyError,
    VLLMBenchServeConfig,
    build_vllm_bench_serve_command,
    check_vllm_bench_available,
    dry_run_vllm_bench_serve,
    ingest_vllm_bench_result,
    run_vllm_bench_serve,
)

__all__ = [
    "CheckResult",
    "BASELINE_MODES",
    "EnvDoctorConfig",
    "EnvDoctorReport",
    "FakeOpenAIServer",
    "FakeOpenAIServerConfig",
    "GeneratedServingConfig",
    "GeneratedWorkload",
    "ManagedProcess",
    "OpenAIClientConfig",
    "OpenAICompatibleClient",
    "OrchestratorConfig",
    "OrchestratorResult",
    "OrchestratorSafetyError",
    "ProcessReadinessTimeout",
    "REAL_VLLM_MODES",
    "ReadinessLevel",
    "RequestMetadata",
    "RequestMetricInput",
    "BaselineComparisonConfig",
    "BaselineComparisonResult",
    "ServingConfigRequest",
    "ServingBenchmarkConfig",
    "ServingBenchmarkResult",
    "ServingReportConfig",
    "ServingReportError",
    "ServingReportResult",
    "ServingRequest",
    "ServingResponseTiming",
    "VLLMBenchAvailability",
    "VLLMBenchCommand",
    "VLLMBenchRunResult",
    "VLLMBenchSafetyError",
    "VLLMBenchServeConfig",
    "WorkloadConfig",
    "build_request_json",
    "build_processes",
    "build_comparisons",
    "build_vllm_bench_serve_command",
    "check_vllm_bench_available",
    "compare_summaries",
    "create_server",
    "dry_run_vllm_bench_serve",
    "format_text_report",
    "generate_serving_config",
    "generate_workload",
    "generate_serving_report",
    "ingest_vllm_bench_result",
    "main",
    "normalize_mode",
    "normalize_workload_name",
    "parse_response_text",
    "read_jsonl",
    "request_from_json_line",
    "run_doctor",
    "run_orchestration",
    "run_baseline_comparison",
    "run_serving_benchmark",
    "run_vllm_bench_serve",
    "summarize_workload",
    "summarize_request_metrics",
    "write_jsonl",
    "write_workload",
]
